# Generated by Django 2.2.4 on 2019-12-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moverrobot',
            old_name='avanzar',
            new_name='accion',
        ),
        migrations.RemoveField(
            model_name='moverrobot',
            name='retroceder',
        ),
    ]
